version: '2.4'
services:
  db:
    container_name: db
    image: flowershop_db
    build:
      context: ./
      dockerfile: Dockerfile.db
    user: postgres
    environment:
      - POSTGRES_USER = root
      - POSTGRES_PASSWORD_FILE = root
      - POSTGRES_DB = flowershop
    ports:
      - 5434:5432
    networks:
      - back-tier
    volumes:
      - type= volume
      - source= psql_data
      - target= /var/lib/postgresql/data

  app:
    container_name: app
    image: flowershop_app
    build: .
    ports:
      - 8080:8080
    networks:
      - back-tier
    depends_on:
      - db

networks:
  back-tier:

volumes:
  psql_data:

